name = "adeep23/cpu_info"
version = "0.1.1"
description = "Grabs info about the CPU."
license = "MIT"
respository = "https://github.com/amol234545/pesde_cpu_info"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.luau",
]

[target]
environment = "lune"
lib = "src/lib.luau"


[indices]
default = "https://github.com/daimond113/pesde-index"
